# Generated by Django 5.2.7 on 2025-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ini', '0002_remove_suscripcion_id_usuario_suscripcion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(max_length=200)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
